In [2]:
import numpy as np

#Stanford numpy tutorial: http://cs231n.github.io/python-numpy-tutorial/#numpy

In [13]:
def somatorios_comproduto(x, grau, com_y=False, y=[]):
    """Faz um somatório dos elementos de x elevados a uma potência.
    Pode incluir os elementos de y multiplicando no somatório
    Exemplo de saída:
    sum(x²)
    ou
    sum(y*x²)
    """
    if com_y:
        x = [(e**grau)*y[i] for i, e in enumerate(x)]
    else:
        x = [e**grau for e in x]
        
    return sum(x)
        
    

def matriz_somatorios(x, grau):
    """Faz a matriz de somatórios
    Exemplo de saída:
    [[sum(x⁰)  sum(x¹)]
     [sum(x¹)  sum(x²)]]
    """
    grau = grau + 1
    X = np.zeros((grau, grau))
    
    for i in range(0, grau):
        for j in range(0, grau):
            X[i,j] = somatorios_comproduto(x, i+j)
            
    return X
    
    
def matriz_independentes(x,y, grau):
    """Faz a matriz de somatórios do membro independente
    Exemplo de saída:
    [sum(y*x⁰)  sum(y*x¹)]
    """
    grau = grau + 1
    X = np.zeros(grau)
    
    for i in range(0, grau):
            X[i] = somatorios_comproduto(x, i, com_y=True, y=y)
            
    return X
    
    
### Setup do problema de MMQ(dados): 
#Grau é o grau do polinômio
grau = 0
x = np.array([-40, 0, 40, 80, 120, 160])
x = [x+273 for x in x]
y = np.array([6900, 8100, 9300, 10500, 11700, 129000])
### Resolvendo
a = matriz_somatorios(x, grau)
b = matriz_independentes(x,y,grau)
resposta = np.linalg.solve(a,b)
resposta

array([ 29250.])

In [8]:
a

array([[  6.00000000e+00,   1.99800000e+03],
       [  1.99800000e+03,   6.93334000e+05]])

In [9]:
b

array([   175500.,  70891500.])

In [10]:
x

[233, 273, 313, 353, 393, 433]